name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.2.4
  - mlflow=1.23
  - pyyaml=5.3.1
  - hydra-core=1.1.1
  - pip:
      - wandb==0.12.9
      - hydra-joblib-launcher==1.1.2
